src/Entity/Ritournelle.php
<?php

namespace App\Entity;

use App\Service\NoDiacritic;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RitournelleRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Ritournelle
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $enigma;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $response;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $clue;

    /**
     * @var Game[]|ArrayCollection
     * @ORM\OneToMany(targetEntity="App\Entity\Game", mappedBy="ritournelle", orphanRemoval=true)
     */
    private $games;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $enabled = true;

    /**
     * @ORM\Column(type="date_immutable")
     */
    private $createdAt;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ritournelles")
     */
    private $user;

    public function __construct()
    {
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEnigma(): ?string
    {
        return $this->enigma;
    }

    public function setEnigma(string $enigma): self
    {
        $this->enigma = $enigma;

        return $this;
    }

    public function getResponse(): ?string
    {
        return $this->response;
    }

    public function setResponse(string $response): self
    {
        $this->response = $response;

        return $this;
    }

    public function getClue(): ?string
    {
        return $this->clue;
    }

    public function setClue(string $clue): self
    {
        $this->clue = $clue;

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->setRitournelle($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->contains($game)) {
            $this->games->removeElement($game);
            // set the owning side to null (unless already changed)
            if ($game->getRitournelle() === $this) {
                $game->setRitournelle(null);
            }
        }

        return $this;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): Ritournelle
    {
        $this->user = $user;

        return $this;
    }

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): Ritournelle
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @ORM\PrePersist
     *
     * @throws \Exception
     */
    public function setCreatedAtValue()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function isValidResponse(string $response): bool
    {
        if (empty(trim($response))) {
            return false;
        }

        return 0 === strcasecmp(
                $this->clean($response),
                $this->clean($this->response)
            );
    }

    public function getRating(): ?int
    {
        if (empty($this->games)) {
            return null;
        }
        $rating = 0;
        $nbResults = 0;
        foreach ($this->games as $game) {
            $results = $game->getResults();
            $nbResults += $results->count();
            foreach ($results as $result) {
                $rating += $result->getRating();
            }
        }
        if (0 == $nbResults) {
            return null;
        }

        return ceil($rating / $nbResults);
    }

    public function getLastRating(): ?int
    {
        $lastGame = $this->getLastGame();
        if (empty($lastGame)) {
            return null;
        }
        $results = $lastGame->getResults();
        if (0 == $results->count()) {
            return null;
        }
        $rating = 0;
        foreach ($results as $result) {
            $rating += $result->getRating();
        }

        return ceil($rating / $results->count());
    }

    private function getLastGame(): ?Game
    {
        /** @var Game|null $lastGame */
        $lastGame = null;
        if (empty($this->games)) {
            return $lastGame;
        }
        foreach ($this->games as $game) {
            if (empty($lastGame) || $lastGame->getPlayedAt() < $game->getPlayedAt()) {
                $lastGame = $game;
            }
        }

        return $lastGame;
    }

    /**
     * On renvoie la moitié des mots aléatoirement.
     */
    public function getRandomHalfWords(): array
    {
        $randomWords = [];
        $words = explode(' ', $this->response);
        $nbWords = floor(count($words) / 2);

        $safeguard = 100;
        for ($i = 0; $i < $nbWords && $safeguard > 0; ++$i) {
            $randomWord = $words[array_rand($words)];
            if (in_array($randomWord, $randomWords)) {
                --$i;
                --$safeguard;
                continue;
            }
            $randomWords[] = $randomWord;
        }

        return $randomWords;
    }

    public function getSimilarity(string $trial): float
    {
        similar_text(
            $this->clean($trial),
            $this->clean($this->response),
            $percent);

        return $percent;
    }

    private function clean(string $text): string
    {
        return trim(preg_replace('/[\'"´’.,;:\/\!§%$£*¤"#\'`\(){}+=@&]/', '', NoDiacritic::filter($text)));
    }
}

src/Controller/RitournelleController.php
<?php

namespace App\Controller;

use App\Entity\CustomResult;
use App\Entity\CustomRitournelle;
use App\Entity\Game;
use App\Entity\Response as ResponseGame;
use App\Entity\Result;
use App\Entity\Ritournelle;
use App\Entity\User;
use App\Form\CommentType;
use App\Form\CustomResponseType;
use App\Form\CustomRitournelleType;
use App\Form\ResponseType;
use App\Form\RitournelleType;
use App\Repository\CustomRitournelleRepository;
use App\Repository\GameRepository;
use App\Repository\ResultRepository;
use App\Repository\RitournelleRepository;
use App\Service\GameManager;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ritournelle", name="ritournelle_")
 */
class RitournelleController extends AbstractController
{
    /**
     * @Route("/enigma", name="enigma")
     *
     * @return Response
     *
     * @throws Exception
     */
    public function enigma(
        EntityManagerInterface $em,
        GameManager $gameManager,
        Request $request
    ) {
        /** @var User $user */
        $user = $this->getUser();

        $game = $gameManager->getTodaysGame();
        $ritournelle = $game->getRitournelle();

        /** @var ResultRepository $resultRepo */
        $resultRepo = $em->getRepository(Result::class);
        $result = $resultRepo->findTodayResult($user, $game);
        $results = $game->getResults();

        $customRitournelleFormView = $previousRitournelle = null;

        // on cherche les informations pour les customs ritournelles
        $previousGame = $gameManager->getPreviousGame();
        if ($previousGame) {
            $previousRitournelle = $previousGame->getRitournelle();
        }
        /** @var CustomRitournelleRepository $customRitournelleRepo */
        $customRitournelleRepo = $em->getRepository(CustomRitournelle::class);
        $customRitournelle = $customRitournelleRepo->findOneBy(['user' => $user, 'createdAt' => new DateTimeImmutable('today')]);
        if (!$customRitournelle) {
            $customRitournelle = new CustomRitournelle();
            $customRitournelleForm = $this->createForm(CustomRitournelleType::class, $customRitournelle);
            $customRitournelleForm->handleRequest($request);
            if ($customRitournelleForm->isSubmitted() && $customRitournelleForm->isValid()) {
                if (empty($result)) {
                    $this->addFlash('success', 'success.defy_ritournelle_waiter');
                } else {
                    $this->addFlash('success', 'success.defy_ritournelle_winner');
                }
                $customRitournelle->setUser($user);
                $em->persist($customRitournelle);
                $em->flush();

                return $this->redirectToRoute('ritournelle_enigma');
            }
            // On n'envoie pas le formulaire si une ritournelle a déjà été envoyée
            $customRitournelleFormView = $customRitournelleForm->createView();
        }
        $customResults = $customRitournelle->getCustomResults();

        // On récupère les ritournelles des autres
        $customRitournelleOthers = $customRitournelleRepo->findOthers(new DateTimeImmutable('today'), $user);
        $customOthers = [];
        foreach ($customRitournelleOthers as $customRitournelleOther) {
            $customOther = [];
            $customOther['ritournelle'] = $customRitournelleOther;
            $customOther['result'] = $customRitournelleOther->getCustomResult($user) ?? '';
            $customOther['form'] = '';

            if (empty($customOther['result'])) {
                $customResponse = new \stdClass();
                $customResponse->customRitournelle = $customRitournelleOther;
                $customResponse->response = '';
                $customResponseForm = $this->createForm(CustomResponseType::class, $customResponse);

                $customResponseForm->handleRequest($request);
                if ($customResponse->customRitournelle === $customRitournelleOther && $customResponseForm->isSubmitted() && $customResponseForm->isValid()) {
                    // on vérifie si la réponse donnée correspond à celle de la ritournelle
                    if ($customRitournelleOther->isValidResponse($customResponse->response)) {
                        // On enregistre en BDD que la réponse a été trouvé
                        $customResult = new CustomResult();
                        $customResult->setUser($user);
                        $customResult->setCustomRitournelle($customRitournelleOther);
                        $em->persist($customResult);
                        $em->flush();

                        // On indique que la réponse en juste
                        $this->addFlash('success', 'ritournelle.right_custom_response');

                        return $this->redirectToRoute('ritournelle_enigma');
                    } else {
                        // on indique que la réponse est fausse
                        $this->addFlash('danger', 'ritournelle.wrong_custom_response');
                    }
                }
                $customResponse->customRitournelle = $customRitournelleOther;
                $customResponse->response = '';
                $customResponseForm = $this->createForm(CustomResponseType::class, $customResponse);
                $customOther['form'] = $customResponseForm->createView();
            }
            $customOthers[] = $customOther;
        }

        // Si la personne n'a toujours pas trouvé, on regarde si elle a soumis le formulaire
        $response = new \stdClass();
        $response->enigma = $ritournelle->getEnigma();
        $response->response = '';
        $responseForm = $this->createForm(ResponseType::class, $response);
        if (empty($result)) {
            $responseForm->handleRequest($request);
            if ($responseForm->isSubmitted() && $responseForm->isValid()) {
                // on vérifie si la réponse donnée correspond à celle de la ritournelle
                if ($ritournelle->isValidResponse($response->response)) {
                    // On enregistre en BDD que la réponse a été trouvé
                    $result = $resultRepo->save($game, $user);
                    // on ajoute à la liste
                    $results[] = $result;

                    // On indique que la réponse en juste
                    $this->addFlash('success', 'ritournelle.right_response');

                    // On va vers un affichage qui gère l'ajout d'un commentaire
                    return $this->redirectToRoute('ritournelle_comment');
                } else {
                    $responseGame = new ResponseGame();
                    $responseGame->setGame($game);
                    $responseGame->setUser($user);
                    $responseGame->setResponse($response->response);

                    $em->persist($responseGame);
                    $em->flush();
                }

                // On indique que la réponse est fausse
                $this->addFlash('danger', 'ritournelle.wrong_response');
            }
        }
        $responseFormView = $responseForm->createView();

        return $this->render(
            'ritournelle/enigma.html.twig',
            compact(
                'customOthers',
                'customResults',
                'customRitournelle',
                'customRitournelleFormView',
                'game',
                'previousRitournelle',
                'responseFormView',
                'result',
                'results',
                'ritournelle',
            )
        );
    }

    /**
     * @Route("/comment", name="comment")
     *
     * @return Response
     *
     * @throws Exception
     */
    public function commentResult(Request $request, EntityManagerInterface $em)
    {
        /** @var User $user */
        $user = $this->getUser();
        /** @var GameRepository $gameRepo */
        $gameRepo = $em->getRepository(Game::class);
        $game = $gameRepo->getTodaysGame();

        /** @var ResultRepository $resultRepo */
        $resultRepo = $em->getRepository(Result::class);
        $result = $resultRepo->findTodayResult($user, $game);
        $results = $resultRepo->findByGame($game);

        if (!$result) {
            return $this->redirectToRoute('ritournelle_enigma');
        }

        $comment = new \stdClass();
        $comment->comment = $result->getComment();
        $comment->rating = $rating = $result->getRating() ?? Result::RATING_DEFAULT;
        $comment->comment_ritournelle = $result->getCommentRitournelle();
        $commentForm = $this->createForm(CommentType::class, $comment);

        $commentForm->handleRequest($request);
        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $result->setComment($comment->comment);
            $result->setRating($comment->rating);
            $result->setCommentRitournelle($comment->comment_ritournelle);
            $em->persist($result);
            $em->flush();

            return $this->redirectToRoute('ritournelle_enigma');
        }
        $commentFormView = $commentForm->createView();

        return $this->render(
            'ritournelle/comment.html.twig',
            compact(
                'commentFormView',
                'results',
                'rating',
            ));
    }

    /**
     * @Route("/list", name="list")
     * @IsGranted("ROLE_ADMIN")
     */
    public function list(EntityManagerInterface $em)
    {
        /** @var RitournelleRepository $ritournelleRepo */
        $ritournelleRepo = $em->getRepository(Ritournelle::class);
        $ritournelles = $ritournelleRepo->findAll();

templates/ritournelle/inc/defy.html.twig
{% trans_default_domain 'ritournelle' %}
<div class="card">
    <div class="card-header" id="headingOne">
        <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse"
                    data-target="#collapseDefy" aria-expanded="true"
                    aria-controls="collapseDefy">
                {{ 'ritournelle.defy_title'|trans }}{% if not customRitournelleFormView %} - {{ 'ritournelle.defy.found'|trans({'nb': customResults|length}) }}{% endif %}
            </button>
        </h5>
    </div>

    <div id="collapseDefy"
         class="collapse {% if customRitournelleFormView %}show{% else %}hide{% endif %}"
         aria-labelledby="headingDefy"
         data-parent="#accordion">
        <div class="card-body">
            {% if customRitournelleFormView %}
                {{ form_start(customRitournelleFormView) }}
                <div class="form-group">
                    {{ form_label(customRitournelleFormView.enigma) }}
                    {{ form_widget(customRitournelleFormView.enigma) }}
                </div>
                <div class="form-group">
                    {{ form_label(customRitournelleFormView.response) }}
                    {{ form_widget(customRitournelleFormView.response) }}
                </div>
                <div class="form-group">
                    {{ form_label(customRitournelleFormView.clue) }}
                    {{ form_widget(customRitournelleFormView.clue) }}
                </div>
                {{ form_widget(customRitournelleFormView.save) }}
                {{ form_end(customRitournelleFormView) }}
            {% else %}
                <div class="container-lg">
                    <div class="row" style="height: 150px">
                        <div class="col-6">
                            <p>
                                {{ 'ritournelle.yours'|trans }}
                            </p>
                            <h5 class="card-title">{{ customRitournelle.enigma }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ customRitournelle.response }}</h6>
                            <p class="card-text">{{ 'ritournelle.clue'|trans }}
                                :<br>{{ customRitournelle.clue }}</p>
                        </div>
                        <div class="col-6 mh-100" style="overflow-y: scroll;">
                            <ul class="list-group">
                                {% for customResult in customResults %}
                                    <li class="list-group-item list-group-item-action">
                                        {{ 'ritournelle.user_found'|trans({'user':customResult.user.username, 'time': customResult.replyAt|date("H") ~ 'h' ~ customResult.replyAt|date("i")}) }}
                                    </li>
                                {% else %}
                                    <p>
                                        {{ 'ritournelle.custom_not_found'|trans }}
                                    </p>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

templates/ritournelle/inc/others.html.twig
{% trans_default_domain 'ritournelle' %}
<div class="card">
    <div class="card-header" id="headingOne">
        <h5 class="mb-0">
            <button class="btn btn-link"
                    data-toggle="collapse"
                    data-target="#collapseOther" aria-expanded="true"
                    aria-controls="collapseOther"
            >
                {{ 'ritournelle.reply_custom'|trans }}{% if customOthers|length > 0 %} - {{ 'ritournelle.defy.other_proposed'|trans({'nb': customOthers|length}) }}{% endif %}
            </button>
        </h5>
        <script type="application/javascript">
            $('[data-toggle="popover"]').popover({
                trigger: 'focus'
            })
        </script>
    </div>

    <div id="collapseOther"
         class="collapse {% if customRitournelleFormView %}hide{% else %}show{% endif %}"
         aria-labelledby="headingOther"
         data-parent="#accordion">
        <div class="card-body">
            <div class="container-lg">
                <div class="row mb-4">
                    {% if result is defined and result is not null %}
                    {{ 'ritournelle.others.notify'|trans }}
                    <div class="col-sm-5">
                        <button role="button" id="notifyButton" class="btn btn-toggle {% if result.customRitournelleNotify %}active{% endif %}" data-toggle="button" aria-pressed="{% if result.customRitournelleNotify %}true{% else %}false{% endif %}" autocomplete="off" onclick="notify(this)">
                            <div class="handle"></div>
                        </button>
                    </div>
                    {% endif %}
                </div>
                <div class="row">
                    <ul class="col-12 list-group">
                        {% for customOther in customOthers %}
                            {% set customRitournelleOther=customOther.ritournelle %}
                            {% set customResultOther=customOther.result %}
                            {% set customFormOther=customOther.form %}
                            <li class="list-group-item list-group-item-action">
                                <div class="row">
                                    <div class="col-6">
                                        <p>
                                            {{ 'ritournelle.proposed'|trans({'%name%': customRitournelleOther.user.username}) }}
                                        </p>
                                        <h5 class="card-title">{{ customRitournelleOther.enigma }}</h5>
                                        <button class="btn btn-secondary" type="button"
                                                data-toggle="collapse"
                                                data-target="#collapse{{ loop.index }}"
                                                aria-expanded="false"
                                                aria-controls="collapseExample">
                                            {{ 'ritournelle.show_clue'|trans }}
                                        </button>
                                        <div class="collapse"
                                             id="collapse{{ loop.index }}">
                                            <p class="mt-2 card-text">
                                                {{ customRitournelleOther.clue }}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        {% if customResultOther %}
                                            <p class="lead">
                                                {{ 'ritournelle.congrats_custom'|trans({'time': customResultOther.replyAt|date("H") ~ 'h' ~ customResultOther.replyAt|date("i")}) }}
                                            </p>
                                        {% else %}
                                            {# on affiche le formulaire pour répondre #}
                                            {{ form_start(customFormOther) }}
                                            <div style="visibility: hidden;">
                                                {{ form_widget(customFormOther.customRitournelle) }}
                                            </div>
                                            <div class="form-group">
                                                {{ form_widget(customFormOther.response) }}
                                            </div>
                                            <div class="form-group">
                                                {{ form_widget(customFormOther.save) }}
                                                {{ form_end(customFormOther) }}
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                                {% if customRitournelleOther.customResults|length > 0 %}
                                <div class="row">
                                    <div class="col-6">
                                        {{ 'ritournelle.custom.found_by'|trans }}&nbsp;
                                        {% for customResult in customRitournelleOther.customResults %}
                                            {{ customResult.user.username }}
                                            {% if not loop.last %}
                                                ,&nbsp;
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                                {% endif %}
                            </li>
                        {% else %}
                            {{ 'ritournelle.no_custom_other'|trans }}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="notifyModal" tabindex="-1" role="dialog" aria-labelledby="notifyModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="notifyModalLongTitle">{{ 'otherRitournelle.notifyModal.title'|trans }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="notify-modal-body">
                blabla
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">{{ 'otherRitournelle.notifyModal.ok'|trans }}</button>
            </div>
        </div>
    </div>
</div>

<style>
    .btn-toggle {
        margin: 0 4rem;
        padding: 0;
        position: relative;
        border: none;
        height: 1.5rem;
        width: 3rem;
        border-radius: 1.5rem;
        color: #6b7381;
        background: #bdc1c8;
    }
    .btn-toggle:focus,
    .btn-toggle.focus,
    .btn-toggle:focus.active,
    .btn-toggle.focus.active {
        outline: none;
    }
    .btn-toggle:before,
    .btn-toggle:after {
        line-height: 1.5rem;
        width: 4rem;
        text-align: center;
        font-weight: 600;
        font-size: 0.75rem;
        text-transform: uppercase;
        letter-spacing: 2px;
        position: absolute;
        bottom: 0;
        transition: opacity 0.25s;
    }
    .btn-toggle:before {
        content: "{{ 'no'|trans({}, 'main') }}";
        left: -4rem;
    }
    .btn-toggle:after {
        content: "{{ 'yes'|trans({}, 'main') }}";
        right: -4rem;
        opacity: 0.5;
    }
    .btn-toggle > .handle {
        position: absolute;
        top: 0.1875rem;
        left: 0.1875rem;
        width: 1.125rem;
        height: 1.125rem;
        border-radius: 1.125rem;
        background: #fff;
        transition: left 0.25s;
    }
    .btn-toggle.active {
        transition: background-color 0.25s;
    }
    .btn-toggle.active > .handle {
        left: 1.6875rem;
        transition: left 0.25s;
    }
    .btn-toggle.active:before {
        opacity: 0.5;
    }
    .btn-toggle.active:after {
        opacity: 1;
    }
    .btn-toggle:before,
    .btn-toggle:after {
        color: #6b7381;
    }
    .btn-toggle.active {
        background-color: #29b5a8;
    }
</style>
<script>
    function reqListener () {
        let text = '';
        if (this.status != 200) {
            disableNotifyButton();
            text = "{{ 'otherRitournelle.notifyModal.problem'|trans }}";
        } else {
            if (this.response.notification_activated) {
                text = "{{ 'otherRitournelle.notifyModal.on'|trans|raw }}";
            } else {
                text = "{{ 'otherRitournelle.notifyModal.off'|trans|raw }}";
            }
        }
        $('#notify-modal-body').html(text);
        $('#notifyModal').modal();
    }
    function notify(element) {
        // si aria-pressed est actuellement à false, alors cela signifie qu'il souhaite être notifié (car ça va passé à true)
        let toBeNotify = element.getAttribute("aria-pressed") == "false";

        let xhr = new XMLHttpRequest();
        xhr.onload = reqListener;
        xhr.open("POST", "{{ path('game_notify', {'id': app.user.id}) }}", true);
        //Send the proper header information along with the request
        xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
        xhr.responseType = 'json';
        let params = "notify="+toBeNotify;
        try {
            xhr.send(params);
        } catch(err) { // instead of onerror
            disableNotifyButton();
        }
    }
    function disableNotifyButton() {
        setTimeout(
            function() {
                document.getElementById('notifyButton').setAttribute('aria-pressed', false);
                document.getElementById('notifyButton').classList.remove('active');
                }, 100);
    }
</script>

templates/ritournelle/inc/previous.html.twig
{% trans_default_domain 'ritournelle' %}
<div class="card">
    <div class="card-header" id="headingOne">
        <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse"
                    data-target="#collapsePrevious" aria-expanded="true"
                    aria-controls="collapsePrevious">
                {{ 'ritournelle.previous'|trans }}
            </button>
        </h5>
    </div>

    <div id="collapsePrevious"
         class="collapse hide"
         aria-labelledby="headingPrevious"
         data-parent="#accordion">
        <div class="card-body">
            <label>{{ 'ritournelle.enigma'|trans }}</label>
            {% set rating = previousRitournelle.lastRating|default(null) %}
            {% if rating > 0 %}
                {% include 'ritournelle/inc/rating.html.twig' with {'disabled': true} %}
            {% endif %}
            <h5 class="card-title">{{ previousRitournelle.enigma|default('') }}</h5>
            <button class="btn btn-secondary" type="button"
                    data-toggle="collapse"
                    data-target="#collapseClue"
                    aria-expanded="false"
                    aria-controls="collapseExample">
                {{ 'ritournelle.show_clue'|trans }}
            </button>
            <div class="collapse"
                 id="collapseClue">
                <p class="mt-2 card-text">
                    {{ previousRitournelle.clue|default('') }}
                </p>
            </div>
            <br>
            <button class="btn btn-secondary mt-2" type="button"
                    data-toggle="collapse"
                    data-target="#collapseResponse"
                    aria-expanded="false"
                    aria-controls="collapseExample">
                {{ 'ritournelle.show_response'|trans }}
            </button>
            <div class="collapse"
                 id="collapseResponse">
                <p class="mt-2 card-text">
                    {{ previousRitournelle.response|default('')|escape }}
                </p>
            </div>
        </div>
    </div>
</div>